# config: ""
# Disable periodically updating ECK telemetry data for Kibana to consume.
disable-telemetry: true
enable-tracing: false
# Enables a validating webhook server in the operator process.
enable-webhook: false
# Enables automatic webhook certificate management.
manage-webhook-certs: true
# Prometheus metrics port. Set to 0 to disable the metrics endpoint.
metrics-port: 0
# Namespaces in which this operator should manage resources. Accepts multiple comma-separated values. Defaults to all namespaces if empty or unspecified.
namespaces: "elastic-manager"
# Namespace the operator runs in. Required.
operator-namespace: "elastic-operator"
# Specifies whether the operator should retrieve storage classes to verify volume expansion support. Can be disabled if cluster-wide storage class RBAC access is not available.
validate-storage-class: true
# Path to the directory that contains the webhook server key and certificate.
# webhook-cert-dir: "{TempDir}/k8s-webhook-server/serving-certs"
# Name of the Kubernetes ValidatingWebhookConfiguration resource. Only used when enable-webhook is true.
webhook-name: "elastic-webhook.k8s.elastic.co"
# webhook-secret: ""
