namespace: elastic-system
resources:
  - 01-elasticsearch.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: elastic-users-secret
    files:
      - filerealm/users
      - filerealm/users_roles
