namespace: elastic-system
resources:
  - elasticsearch.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: elastic-roles-secret
    files:
      - filerealm/users
      - filerealm/users_roles
